language: node_js
node_js:
  - "v6.1.0"
notifications:
  slack: rubeniskov:I82ZGuYOEQrhl29wBbQFEdjP#nkinect
cache:
  bundler: true
  directories:
  - node_modules
  - vendor
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git-core build-essential cmake libusb-1.0
  - mkdir -p vendor && cd vendor;
    git clone https://github.com/OpenKinect/libfreenect && cd libfreenect;
    mkdir -p build && cd build;
    cmake -L ..;
    make -j$(nproc);
    sudo make install
install:
  - npm install
before_script:
  - npm run build
script:
  - npm test
