language: node_js
node_js:
  - "v6.1.0"
cache:
  bundler: true
  directories:
  - node_modules
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y freenect
install:
  - npm install
script:
  - npm test
