language: node_js
node_js:
  - "v8.0.0"
  - "v7.0.0"
  - "v6.0.0"
  - "v5.0.0"
  - "v4.1.0"
notifications:
  slack: rubeniskov:I82ZGuYOEQrhl29wBbQFEdjP#nkinect
cache:
  bundler: true
  directories:
  - node_modules
  - session
before_install:
  - wget "https://drive.google.com/uc?export=download&id=0B-npeLS9ojmzSWVnVEZkUnBXaU0" -O - | tar -xz
  - sudo apt-get -qq update
  - sudo apt-get install -y git-core build-essential cmake libusb-1.0
  - mkdir -p vendor && cd vendor;
    if [ -d libfreenect ]; then git clone https://github.com/OpenKinect/libfreenect; fi;
    cd libfreenect;
    mkdir -p build && cd build;
    cmake -L ..;
    make -j$(nproc);
    sudo make install
install:
  - npm install
before_script:
  - npm run build
script:
  - npm test
